sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- node
before_script:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#- sleep 3
- npm install -g grunt-cli npm
- npm install
#- node_modules/protractor/bin/webdriver-manager update --gecko=false
env:
  global:
    secure: AZTMyxQS7zCMYjkMCBFD17qmUfnpVdg78/LksBGTV52hVnId5Yyn7OHUzm70kqTrbzqSnnb9ipUO1NEgFNaoxwldavesU/oM0W/EyZ52VNk0hRbseF3TbI83ewCT5X7yIsVeWaUFSDu44g26He2BXfo8wlVP7meG5sfBpV8qNSrOk8MmXEKEheSE9ghv7sUQQpQI2V2/EsWm/CqAh7++70oq1Bdp0U6xzQUw6GRL7xEHYgaXbYYRaHixvzHamjO9enBgUXoZ/d9h+gQlaTTJ0EdgltAkzfewYubb9FAsf7Z0OVFz1bBx2UXOOiW1V00Q76bbOBK7nUt4M05CWhPq1u31JleFVpt4MO9s5Og927fH12tZ5A+3Ss0EN7zrSn7GX7P8YdhDyMBlua9YHZG40GJp7Sb4moB66Y6uZdVN0qCD6a4Jxba+a9l3tCIJCIfEMvY+Xl7epr4Z+fVss2eQGrZPgUgpYNYCE14VK28oLYwCA84cgTHj6CrwbqDKUgk73CfP8f7LD7N9a9pl4rcdflTYWa0iIy71zaAuNflSwJdtoTJEwzT8GeIJlNkakOLVUiOa+jIW9Ah1JY3Pdk30BlczvxuNmMjSx52IR+QS7hNO3Z+7BngvYN3tlM8cpwFQzG/Y2dNiivsrkq0dSWmhjajMg8KNzyeWL5wCYKOKrF0=
